formatter: markdown table

settings:
  anchor: true
  color: true
  default: true
  escape: true
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true

recursive:
  enabled: false

sort:
  enabled: true
  by: required

output:
  file: README.md
  mode: replace
